openapi: 3.0.3
info: { title: OPDI_SKPR Device API, version: 0.1.0 }
paths:
  /api/v1/system/info:
    get: { summary: Get device info, responses: { '200': { description: OK } } }
# Replace with full spec from SRD Appendix I2