name: build
on:
  push:
  pull_request:

jobs:
  esp32p4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5
          target: esp32p4
          path: .
          command: |
            idf.py set-target esp32p4
            idf.py build
            idf.py size-components

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
